---
# Example playbook using a jinja2 template
- hosts: all
  vars:
    Address: '192.168.3.101'
    Name: 'webadmin1'
  tasks:
    - name: Ansible Template Example
      template:
        src: welcome.j2
        dest: /home/webadmin1/welcome.txt
      remote_user: root
