---
- name: Create users
  hosts: all
  tasks:
  - name: Create users
    user:
      name: "{{ item }}"
      state: present
      shell: "/bin/bash"
      password: "{{ default_password | password_hash('sha512', 'A512') }}"
    loop:
      - bob
      - ted
      - sally
